// <auto-generated />
using System;
using Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250917225727_seedData")]
    partial class seedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.Product", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Code");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Code = "P001",
                            Category = "Electronics",
                            Discount = 0.10m,
                            ImageUrl = "https://cdn.mos.cms.futurecdn.net/FUi2wwNdyFSwShZZ7LaqWf.jpg",
                            Name = "Laptop",
                            Price = 999.99m,
                            Quantity = 10
                        },
                        new
                        {
                            Code = "P002",
                            Category = "Electronics",
                            Discount = 0.05m,
                            ImageUrl = "https://m.media-amazon.com/images/I/61fh21u3DJL.jpg",
                            Name = "Smartphone",
                            Price = 499.99m,
                            Quantity = 20
                        },
                        new
                        {
                            Code = "P003",
                            Category = "Accessories",
                            Discount = 0.15m,
                            ImageUrl = "https://m.media-amazon.com/images/I/61kcjN3yo+L._UF894,1000_QL80_.jpg",
                            Name = "Headphones",
                            Price = 79.99m,
                            Quantity = 50
                        },
                        new
                        {
                            Code = "P004",
                            Category = "Home Appliances",
                            Discount = 0.20m,
                            ImageUrl = "https://i5.walmartimages.com/seo/Mr-Coffee-5-Cup-Programmable-Coffee-Maker-25-oz-Mini-Brew-Brew-Now-or-Later-Black_972164db-9b9b-42e2-9463-80f40fb360e3.2423b7d6d6d77ec31ed140a0cece9662.jpeg",
                            Name = "Coffee Maker",
                            Price = 39.99m,
                            Quantity = 15
                        },
                        new
                        {
                            Code = "P005",
                            Category = "Electronics",
                            Discount = 0.10m,
                            ImageUrl = "https://i5.walmartimages.com/asr/78ecb78a-f45e-40c9-98c2-e059bc4e93b6.781d30e03254cb41d2297474de4d50c0.jpeg",
                            Name = "Gaming Console",
                            Price = 299.99m,
                            Quantity = 5
                        },
                        new
                        {
                            Code = "P006",
                            Category = "Home Appliances",
                            Discount = 0.25m,
                            ImageUrl = "https://cdn.mafrservices.com/pim-content/EGY/media/product/647543/1737017022/647543_main.jpg",
                            Name = "Electric Kettle",
                            Price = 24.99m,
                            Quantity = 30
                        },
                        new
                        {
                            Code = "P007",
                            Category = "Electronics",
                            Discount = 0.10m,
                            ImageUrl = "https://m.media-amazon.com/images/I/71pbEc1KO3L._AC_SL1500_.jpg",
                            Name = "Smartwatch",
                            Price = 199.99m,
                            Quantity = 12
                        },
                        new
                        {
                            Code = "P008",
                            Category = "Accessories",
                            Discount = 0.15m,
                            ImageUrl = "https://m.media-amazon.com/images/I/81oRzXfs2zL._UF894,1000_QL80_.jpg",
                            Name = "Bluetooth Speaker",
                            Price = 49.99m,
                            Quantity = 25
                        });
                });

            modelBuilder.Entity("Data.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
